Update deploy-lambda.yml

diff --git a/.github/workflows/deploy-lambda.yml b/.github/workflows/deploy-lambda.yml
--- a/.github/workflows/deploy-lambda.yml
+++ b/.github/workflows/deploy-lambda.yml
@@ -69,18 +69,17 @@ jobs:
           EC2_NAME=$(terraform output -raw ec2_instance_name)
           echo "ec2_name=$EC2_NAME" >> $GITHUB_OUTPUT
           echo "EC2_NAME_TAG=$EC2_NAME" >> $GITHUB_ENV
-          
+
       - name: 💻 Check & Install AWS CLI if not present
         run: |
           if ! command -v aws &> /dev/null; then
-           echo "AWS CLI not found. Installing..."
-           curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-           unzip -q awscliv2.zip
-           sudo ./aws/install
+            echo "AWS CLI not found. Installing..."
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip -q awscliv2.zip
+            sudo ./aws/install
           else
-           echo "✅ AWS CLI already installed: $(aws --version)"
+            echo "✅ AWS CLI already installed: $(aws --version)"
           fi
-
 
       - name: ⏳ Wait for EC2 to register in SSM
         env:
@@ -125,11 +124,11 @@ jobs:
             --document-name "AWS-RunShellScript" \
             --comment "Install PostgreSQL 15" \
             --parameters 'commands=[
-              "#!/bin/bash",
-              "set -euxo pipefail",
+              "export DEBIAN_FRONTEND=noninteractive",
+              "set -eux",
               "apt-get update -y",
               "apt-get install -y curl gnupg2 lsb-release ca-certificates sudo software-properties-common",
-              "curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /usr/share/keyrings/postgresql.gpg",
+              "curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --batch --yes --dearmor -o /usr/share/keyrings/postgresql.gpg",
               "echo \"deb [signed-by=/usr/share/keyrings/postgresql.gpg] http://apt.postgresql.org/pub/repos/apt noble-pgdg main\" > /etc/apt/sources.list.d/pgdg.list",
               "apt-get update -y",
               "apt-get install -y postgresql-15 postgresql-client-15",
