Update destroy-multi-api-deployment.yml

diff --git a/.github/workflows/destroy-multi-api-deployment.yml b/.github/workflows/destroy-multi-api-deployment.yml
--- a/.github/workflows/destroy-multi-api-deployment.yml
+++ b/.github/workflows/destroy-multi-api-deployment.yml
@@ -7,7 +7,9 @@ on:
         description: 'Environment to destroy (dev/staging/prod)'
         required: true
         default: 'dev'
-
+      confirm_destroy:
+        description: 'Type "destroy" to confirm deletion'
+        required: true
 env:
   AWS_REGION: eu-west-1
   TF_BUCKET: my-terraform-state-bckt4321
@@ -34,7 +36,14 @@ jobs:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ env.AWS_REGION }}
-
+          
+      # Conditional step to prevent accidental destroy
+      - name: Check for Destroy Confirmation
+        if: github.event.inputs.confirm_destroy != 'destroy'
+        run: |
+          echo "Error: Destroy confirmation not provided. Aborting."
+          exit 1
+          
       - name: Destroy CloudWatch
         run: |
           cd infra/cloudwatch
@@ -70,6 +79,18 @@ jobs:
           cd infra/ssm
           terraform init -backend-config="bucket=${TF_BUCKET}" -backend-config="key=${{ github.event.inputs.ENV }}/ssm/terraform.tfstate"
           terraform destroy -auto-approve -var-file="${{ github.event.inputs.ENV }}.tfvars"
+      - name: Initialize Terraform
+        working-directory: infra/s3 # Or root if your destroy works from there
+        run: |
+          terraform init \
+            -backend-config="bucket=${TF_BUCKET}" \
+            -backend-config="key=${{ github.event.inputs.environment }}/s3/terraform.tfstate"
+
+
+      - name: Terraform Destroy Plan
+        working-directory: infra/s3
+        run: terraform plan -destroy -var-file="${{ github.event.inputs.environment }}.tfvars"
+    
 
       - name: Destroy S3
         run: |
