Update multi-api-deployment.yml

diff --git a/.github/workflows/multi-api-deployment.yml b/.github/workflows/multi-api-deployment.yml
--- a/.github/workflows/multi-api-deployment.yml
+++ b/.github/workflows/multi-api-deployment.yml
@@ -147,8 +147,17 @@ jobs:
            -var="tf_state_bucket=$TF_STATE_BUCKET" \
            -var="environment=${{ github.event.inputs.ENV }}"
            
+   
+          export TF_CLI_ARGS="-no-color"
           ECR_REPO_URL=$(terraform output -raw ecr_repository_url 2>/dev/null | tr -d '\r')
-          echo "ECR_REPO_URL=${ECR_REPO_URL}" >> $GITHUB_ENV
+
+  
+          if [[ "$ECR_REPO_URL" == *"::"* ]]; then
+           echo "ECR_REPO_URL contains invalid '::'. Skipping export."
+           exit 1
+          fi
+
+          echo "ECR_REPO_URL=$ECR_REPO_URL" >> $GITHUB_ENV
 
       - name: Terraform Apply SSM
         id: ssm
